/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_xuantang_nativelearning_JNIDemo */

#ifndef _Included_com_xuantang_nativelearning_JNIDemo
#define _Included_com_xuantang_nativelearning_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xuantang_nativelearning_JNIDemo
 * Method:    stringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xuantang_nativelearning_JNIDemo_stringFromNative
  (JNIEnv *, jobject, jstring param);

JNIEXPORT jobject JNICALL Java_com_xuantang_nativelearning_JNIDemo_create
        (JNIEnv *, jclass type);

JNIEXPORT jstring JNICALL Java_com_xuantang_nativelearning_JNIDemo_changeName
        (JNIEnv *, jobject instance, jobject job, jstring name);

#ifdef __cplusplus
}
#endif
#endif
